#! /usr/bin/env python

# Script to run the elastic model and compare the reference Demand with the 
# solution from temoa_elastic_model.py.
# Usage: Same as temoa_elastic_model.py and temoa_model.py
# Additional requirement: Should provide price data (price.dat) generated by price_generatoty.py. 

from coopr.pyomo import *
from temoa_elastic_model import temoa_create_elastic_model, temoa_create_model_container
from temoa_lib import temoa_solve

model = temoa_create_elastic_model()
model_data = temoa_create_model_container(model)
temoa_solve(model_data)
instance = model_data.instance
from temoa_elastic_rules import PriceSegment_rule, DemandSegment_midpoint

for p, s, d, dem  in sorted(instance.V_Demand.keys()):
    key = p, s, d, dem
    print "%35s elast %4g lb %8g ref %8g level %8g ub %8g ref Price %8g elast Price %8g" % \
        (key, value(instance.Elast[key]), instance.V_Demand[key].lb,
            value(instance.Demand[p, dem]) * value(instance.DemandSpecificDistribution[s, d, dem]),
            value(instance.V_Demand[key]), instance.V_Demand[key].ub,
            value(instance.Price[key]), instance.DemandElasticityConstraint[key].dual)
